function T=oldCruiseMetaFiles_excelOutput()
%in the process of going through the old Metacruise file names I ran into
%an issue where the old_cruise_meta.json file identifies floats by WMO and
%cruise name. Whereas the .meta files are named with the convention:
%     AOML#_TransmissionID#.meta 
%This makes it almost impossible to visually & quickly work with the data
%for identifying what information (deployment platform/deployment ID) 
%inside of which meta files needs to be updated. So I have made this code
%which outputs all of the relevant information into an excel sheet 
%Note that my finalized excel sheet has human-work done to it, and if you
%run block 1 & 2 again to get the original excel sheet out it will not
%be organized as the finalized one is. The finalized, corrected document is
%called old_cruise_meta_organized_SN3.xlsx
% DO NOT OVERWRITE THAT DOCUMENT. 

%% BLOCK 1 
% in this block I go into the directory that holds the old meta data
% files and extract only the meta data files -- there are a few dot files 
% at the beginning and other files at the end, we exclude those. 

sourceMetaFiles = '/argus/data1/argo/metadata/aoml/'
cd(sourceMetaFiles)
metaFilesStruct = dir(sourceMetaFiles);
metaFiles_allnames = {metaFilesStruct(1:end).name};
    %pat = digitsPattern(4) + "_" + (digitsPattern(5)|digitsPattern(6)) + (".meta"|".meta_old");
    %left the above here as an example, you can create all kinds of useful
    %patterns for finding files!
pat = digitsPattern(4)|digitsPattern(5);
metaFiles_ind = startsWith(metaFiles_allnames(1:end), pat, 'IgnoreCase', true);
metaFiles = metaFiles_allnames(metaFiles_ind==1);

%% BLOCK 2
%easyReadTable = table;%(aoml_num, wmo_num, deployment_platform, deployment_cruise_id)
pat00 = ("WMO ID number"|"deployment type"|"deployment platform"|"deployment cruise id"|"launch time");
pat0 = "internal ID number";
pat1 = "WMO ID number";
pat2 = "deployment type";
pat3 = "deployment platform";
pat4 = "deployment cruise id";
pat5 = "launch time [dd mm yyyy hh mm (Z)]";
    %pat5a = digits(4);

for i=1:length(metaFiles)
    %fid = fopen(metaFiles{i});
    all_file_lines = readlines(metaFiles{i}); 
    mask = startsWith(all_file_lines, pat00, 'IgnoreCase', true);
    lines_needed = all_file_lines(mask==1); %technically you can do this only using the 'extractAfter' command, but I wanted to be sure that we captured the info even if there were case issues

    aomlnum = strtrim( extractAfter(all_file_lines(startsWith(all_file_lines, pat0, 'IgnoreCase', true)==1), pat0));
    WMOnum = strtrim( extractAfter(all_file_lines(startsWith(all_file_lines, pat1, 'IgnoreCase', true)==1), pat1));
    deployment_Type = strtrim( extractAfter(all_file_lines(startsWith(all_file_lines, pat2, 'IgnoreCase', true)==1), pat2));
    deployment_Platform = strtrim( extractAfter(all_file_lines(startsWith(all_file_lines, pat3, 'IgnoreCase', true)==1), pat3));
    deployment_CruiseID = strtrim( extractAfter(all_file_lines(startsWith(all_file_lines, pat4, 'IgnoreCase', true)==1), pat4));
    deployment_day_mo_year = strtrim( extractAfter(all_file_lines(startsWith(all_file_lines, pat5, 'IgnoreCase', true)==1), pat5));

    if isempty(aomlnum)==1
        aomlnum= "auto-generated by code, no input found";
    end
    if isempty(WMOnum)==1
        WMOnum = "auto-generated by code, no input found";
    end
    if isempty(deployment_Type)==1 
        deployment_Type = "auto-generated by code, no input found";
    end 
    if isempty(deployment_Platform)==1
        deployment_Platform = "auto-generated by code, no input found";
    end
    if isempty(deployment_CruiseID)==1
        deployment_CruiseID = "auto-generated by code, no input found";
    end
    if isempty(deployment_day_mo_year)==1
        deployment_day_mo_year = "auto-generated by code, no input found";
    end

    T(i,1:6) = table(aomlnum, WMOnum, deployment_Type, deployment_Platform, deployment_CruiseID, deployment_day_mo_year);

end

filename = 'old_cruise_metadata_organized_for_sorting.xlsx'
writetable(T,filename,'Sheet',1);

%% Block 3 
% This code just adds the aoml number as a column to the excel sheet -- the
% reason this is not just part of the code above is that I had already
% started to work on the excel document above when I realized i needed the
% aoml number. So alli e'ta.  
% Define paths
sourceMetaFiles = '/argus/data1/argo/metadata/aoml/'
cd(sourceMetaFiles)
metaFilesStruct = dir(sourceMetaFiles);
metaFiles_allnames = {metaFilesStruct(1:end).name};

% Filter by digit-patterned filenames
pat = digitsPattern(4)|digitsPattern(5)|digits(6) +"_"+ digitsPattern(4)|digitsPattern(5)|digitsPattern(6)|digits(7);
metaFiles_ind = startsWith(metaFiles_allnames(1:end), pat, 'IgnoreCase', true);
metaFiles = metaFiles_allnames(metaFiles_ind==1);

% Patterns to search for
%insert here an input statment so that people can select between what
%fields they can change in the meta file 
%pat0a = ("internal ID number" | "WMO ID number" | "float serial number");
pat1a = "internal ID number";
pat2a = "WMO ID number";
pat3a = "float serial number";
pat4a = "deployment type";
pat5a = "deployment platform";
pat6a = "deployment cruise ID";
pat7a = "PI    ";
pat8a = "launch time [dd mm yyyy hh mm (Z)]";


% Read Excel file
excelData = readtable('old_cruise_meta_organized_SN2', 'Sheet', 'Sheet1');
excelWMO = string(excelData.WMOnum);     % Adjust column names if needed
excelAOML = string(excelData.aomlnum);   % Adjust column names if needed

% Ensure AOML numbers are zero-padded to 5 digits
excelAOML_padded = pad(excelAOML, 5, 'left', '0');

% % Preallocate new column
% %excelData.FloatSerialNumber = strings(height(excelData), 1);
% excelData.PI = strings(height(excelData), 1);

% % Initialize log for unmatched files
% % unmatchedLog = table('Size', [0 4], ...
% %     'VariableTypes', ["string", "string", "string", "string"], ...
% %     'VariableNames', ["FileName", "AOML", "WMO", "FloatSerial"]);
% unmatchedLog = table('Size', [0 4], ...
%     'VariableTypes', ["string", "string", "string", "string"], ...
%     'VariableNames', ["FileName", "AOML", "WMO", "PI"]);

% Process metadata files
for i = 1:length(metaFiles)
    all_file_lines = readlines(metaFiles{i}); 

    aomlnum = strtrim( extractAfter(all_file_lines(startsWith(all_file_lines, pat1a, 'IgnoreCase', true)), pat1a));
    WMOnum = strtrim( extractAfter(all_file_lines(startsWith(all_file_lines, pat2a, 'IgnoreCase', true)), pat2a));
    floatSerialNum = strtrim( extractAfter(all_file_lines(startsWith(all_file_lines, pat3a, 'IgnoreCase', true)), pat3a));
    floatPI = strtrim( extractAfter(all_file_lines(startsWith(all_file_lines, pat4a, 'IgnoreCase', true)), pat4a));


    if isempty(aomlnum), aomlnum = "auto-generated by code, no input found"; end
    if isempty(WMOnum), WMOnum = "auto-generated by code, no input found"; end
    %if isempty(floatSerialNum), floatSerialNum = "auto-generated by code, no input found"; end
    if isempty(floatPI) || all(isspace(floatPI)), floatPI = "auto-generated by code, no input found"; end


    aomlnum_padded = pad(aomlnum, 5, 'left', '0');
    rowMatch = find(excelWMO == WMOnum & excelAOML_padded == aomlnum_padded);

    if ~isempty(rowMatch)
        %excelData.FloatSerialNumber(rowMatch(1)) = floatSerialNum;
        excelData.PI(rowMatch(1)) = floatPI;
        fprintf('Match found and updated for file: %s\n', metaFiles{i});
    else
        fprintf('No match found for file: %s\n', metaFiles{i});
        %unmatchedLog = [unmatchedLog; {metaFiles{i}, aomlnum, WMOnum, floatSerialNum}];
        unmatchedLog = [unmatchedLog; {metaFiles{i}, aomlnum, WMOnum, floatPI}];
    end
end

% Save updated Excel and unmatched log
%writetable(excelData, 'old_cruise_meta_organized_SN2_PIs.xlsx', 'Sheet', 'Sheet1');
writetable(unmatchedLog, 'unmatched_metadata_log_PIs.xlsx');


%% BLOCK 4


%% 

